name: API report

on: [push, pull_request]

jobs:
  report:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: 22.23.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Check files
        run: ls built

      - name: API report
        run: pnpm run api-prod

      - name: Show report
        if: always()
        run: cat temp/mfm-js.api.md
